# Generated by Django 2.2.5 on 2022-06-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220603_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gemder',
            new_name='gender',
        ),
    ]
